### ISSUE TITLE
Initial Feedback

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest-website#3]
<img width="639" alt="Screenshot 2023-12-13 at 1 32 27 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/d9d39c3f-0186-4992-984c-06a060a0c18f">

- Fix opacity on the left
- Add Snapshot Service link to section below
- "Documentation" should link to Forest docs, not section below

<img width="1258" alt="Screenshot 2023-12-13 at 1 32 17 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/905ee62e-e6b9-4aa1-82c0-29723d990075">

- Excessive dead space -> move next section up
- "implementation for the Filecoin protocol" -> "implementation of the Filecoin protocol"

<img width="257" alt="Screenshot 2023-12-13 at 1 41 01 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/6052f6fc-04f7-4c3c-b17b-301dd4ac6a69">

- "consensus data" -> "chain data"

<img width="612" alt="Screenshot 2023-12-13 at 1 41 39 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/8a2e6329-e111-4172-a63d-9923d9c01692">

- Replace with "All this is available with minimal hardware."
  - Rationale: "reference Filecoin node" is vague, but we also maybe don't want to say Lotus. Hence my suggestion to change the language to a more positive phrasing.

<img width="590" alt="Screenshot 2023-12-13 at 1 31 39 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/28849091-584e-4c18-a141-6b9a7659a9c2">

- Replace with "Join our beta program to help make Forest the best it can be. Let us know how we can support your needs."
  - Rationale: "respected on the roadmap" is a weird phrasing; "early" is not really relevant; "feedback" is on Forest, not the use cases;

<img width="1048" alt="Screenshot 2023-12-13 at 1 32 07 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/2afde477-4c4c-4126-a173-c15f8a506cfc">

- I'm confused what these are. I realize they are steps of some sort related to the beta program, but having them here and clickable seems to neglect a lot of necessary context.
- "Bootstrap your custom full node" - nothing is "custom" afaik, "bootstrap" is potentially confusing in this context as it's not a bootstrap node

<img width="1229" alt="Screenshot 2023-12-13 at 1 31 30 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/8b55d84c-cb75-42bc-bef4-3363872a28d9">

- The intent with this is to show the comparison. I perceive the current format as simply showing the specs for each, they aren't really contrasted.

<img width="1229" alt="Screenshot 2023-12-13 at 1 33 16 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/645759fb-5408-4c88-a0a5-ec3739fdf8b5">

- Would be good to add titles "Docker", "Binaries", "Build from Source"
- "To run Forest in Docker," can be removed from the sentence as it's implicit
- Replace "To Install Forest..." -> "Get the latest release builds"
- Replace "To build Forest...." -> "Get the latest source code"

<img width="1151" alt="Screenshot 2023-12-13 at 1 33 33 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/18e77376-299c-4837-9416-0893a8fbbd6d">

- IMO this should be in the docs, not the landing page. Some of these points could be considered features and included above.

<img width="1231" alt="Screenshot 2023-12-13 at 1 34 02 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/54d2e315-e661-4efb-958b-cd267c2adc93">

- This also seems like it should be in documentation, not here
- The left image could be used in the top section to fill space
- Both images are identical 🤔 

<img width="1337" alt="Screenshot 2023-12-13 at 2 34 02 PM" src="https://github.com/ChainSafe/forest-website/assets/14164624/c6c7f43c-f000-4007-917b-2a5d5dd72d81">

- Perhaps this section should be titles "Learn More"
- "Github Pages" -> "Documentation" (being on GH pages is irrelevant to the user, should also be remove from description text)
- Remove "conditions of the"
- "API Reference" -> "Rust Docs"

**Comment by sweetpea22** [comment]
hi, thanks for the review. appreciate it :)

all UI change requests you've made are now implemented except the table looks the same mobile. i'll share with you the updated staging link upon next commit to get your thoughts on the new table. 

i showed copy suggestions to Colin and Ria from marketing, they have accepted all copy changes except the following: 

> "Documentation" should link to Forest docs, not section below

generally we would like to avoid external linking in the top bar.  "documentation" in footer links out externally tho. lmk if there are still strong feelings about this. 

>re: beta testing I'm confused what these are. I realize they are steps of some sort related to the beta program

i added a title, i hope that helps? maybe it needs a full redesign. 

> re: binaries section. IMO this should be in the docs, not the landing page.

i think we need this clearly display what forest is capable of.

cc: @q9f @lerajk
