### ISSUE TITLE
Subsequent Feedback

### ISSUE THREAD

**Issue by q9f** [ChainSafe/forest-website#4]
This turned our so nice! Good work!

Landing: 

- "Reach the Team" is linked to a third-party web form. Let's either implement a web form on our website (we don't need a service for that) or link directly to GitHub discussions (preferred). If we want a private contact, we can put it in the footer.
- I love the mouse-over effect!

Snapshot service:

- I love the visual explanation of the different snapshot formats!
- 404 https://forest.chainsafe.io/calibnet/snapshot-latest
- 404 https://forest.chainsafe.io/mainnet/snapshot-latest

Running a node:

- This turned out really nicely!
- On the right terminal the CLI command should be: forest-cli sync status
- Can we also add the forest-cli command for Calibnet? Or if it is the same, lets remove the "on mainnet" piece.

**Comment by sweetpea22** [comment]
hi! the latest commit [0b868c4](https://github.com/ChainSafe/forest-website/commit/0b868c45670ec307d0f9240cd7c7d5d750225523) pushes all fixes, i'm directing "Reach the team" button to github discussions for now. I think it's nice to show the feedback in a public place. Let me know if you want the web form instead tho
